project/server/main/views.py
# project/server/main/views.py


from flask import render_template, Blueprint

from ..updates import get_updates
from ..builds import get_builds
from ..bugs import get_bugs
from ..changelogs import get_changelogs
from ...server import cache

main_blueprint = Blueprint("main", __name__)


@main_blueprint.route("/")
def home():
    return render_template("main/home.html")


@main_blueprint.route("/packages/")
@main_blueprint.route("/packages/<package_name>/")
def packages(package_name=None):
    if not package_name:
        return home()
    else:
        return render_template("main/package-overview.html",
                               package_name=package_name)


@cache.cached(timeout=120)
@main_blueprint.route("/packages/<package_name>/builds")
def package_builds(package_name):
    builds = get_builds(package_name)
    return render_template("main/package-builds.html",
                           package_name=package_name, builds=builds)


@cache.cached(timeout=120)
@main_blueprint.route("/packages/<package_name>/updates")
def package_updates(package_name):
    updates = get_updates(package_name)
    return render_template("main/package-updates.html",
                           package_name=package_name, updates=updates)


@cache.cached(timeout=600)
@main_blueprint.route("/packages/<package_name>/bugs")
def package_bugs(package_name):
    bugs = get_bugs(package_name)
    return render_template("main/package-bugs.html",
                           package_name=package_name, bugs=bugs['bugs'],
                           open_bugs=bugs['open_bugs'],
                           open_bugs_url=bugs['open_bugs_url'],
                           blocker_bugs=bugs['blocker_bugs'],
                           blocker_bugs_url=bugs['blocker_bugs_url'],
                           )


@main_blueprint.route("/packages/<package_name>/problems")
def package_problems(package_name):
    return render_template("main/package-problems.html",
                           package_name=package_name)


@main_blueprint.route("/packages/<package_name>/contents")
def package_contents(package_name):
    return render_template("main/package-contents.html",
                           package_name=package_name)


@cache.cached(timeout=600)
@main_blueprint.route("/packages/<package_name>/changelog")
def package_changelog(package_name):
    changelog = get_changelogs(package_name)
    return render_template("main/package-changelog.html",
                           package_name=package_name,
                           changelog=changelog)


@main_blueprint.route("/packages/<package_name>/sources")
def package_sources(package_name):
    return render_template("main/package-sources.html",
                           package_name=package_name)

fedoracommunity/client/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Fedora Packages Search{% endblock %}</title>
  <script src="{{ url_for('system_static', component='jquery', filename='1/jquery.min.js') }}"></script>
  <script src="{{ url_for('system_static', component='jquery_ui', filename='jquery-ui.min.js') }}"></script>
  <link rel="stylesheet" type="text/css" href="https://apps.fedoraproject.org/global/fedora-bootstrap-1.0.2/fedora-bootstrap.css" media="all" />
  <link rel="stylesheet" href="{{ url_for('system_static', component='jquery_ui', filename='jquery-ui.min.css') }}" />
  <link href="{{ url_for('system_static', component='patternfly', filename='css/patternfly.min.css') }}" rel="stylesheet" media="screen, print">
  <link rel="stylesheet" href="{{ url_for('system_static', component='patternfly', filename='css/patternfly-additions.min.css') }}">
  <link href="{{ url_for('static', filename='custom-styles.css') }}" rel="stylesheet" media="screen, print">
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="{{ url_for('system_static', filename='html5shiv.min.js') }}"></script>
  <script src="{{ url_for('system_static', filename='respond.min.js') }}"></script>
  <![endif]-->
  <!-- IE8 requires jQuery and Bootstrap JS to load in head to prevent rendering bugs -->
  <!-- IE8 requires jQuery v1.x -->
  <script src="{{ url_for('system_static', component='jquery', filename='1/jquery.min.js') }}"></script>
  <script src="{{ url_for('system_static', component='bootstrap_scss', filename='js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('system_static', component='datatables', filename='js/jquery.dataTables.js') }}"></script>
  <script src="{{ url_for('system_static', component='patternfly', filename='js/patternfly.min.js') }}"></script>
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='fedora.css') }}">
  <link rel="stylesheet" type=text/css href="{{ url_for('static', filename='bootstrap.min.css') }}">
   <link rel=stylesheet type=text/css href="{{ url_for('static', filename='style-overwrite.css') }}">
</head>
<body>

  {% macro nav_element(tab_name, tab_title, icon,  href) %}
  <li class="{% if selected_tab == tab_name %}active{% endif %}">
    <a href="{{ href }}"> <span class="{{icon}}"></span> {% if "pficon" not in icon %}&nbsp;{%endif%}
      {{ tab_title }}
    </a>
  </li>
  {% endmacro %}


   <!-- CONTENT -->
  <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
              {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}




  </div>

  <!-- child template -->
  <div id="content">
    {% block content %}{% endblock %}
  </div>
  {% include 'footer.html' %}
</body>
</html>

fedoracommunity/client/templates/_helpers.html
{% macro initialize_datatables(order="desc", column=0) %}
  <script>
  // Initialize Datatables
  $(document).ready(function() {
    $('.datatable').dataTable({
      "order": [[ {{column}}, '{{ order }}' ]],
      "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, 'All']],
      dom:
        "<'dataTables_header'<'dataTables_filter'f><'dataTables_info'i>>" +
        "<'row'<'col-sm-12'tr>>" +
        "<'row table_footer'<'col-sm-6 dataTables_length'l><'col-sm-6 dataTables_info'p>>"
    });

    $('[name="DataTables_Table_0_length"]').change(function() {
      if (this.value == -1) {
        $("#DataTables_Table_0_paginate").hide();
      } else {
        $("#DataTables_Table_0_paginate").show();
      }
    });
  });
  </script>
{% endmacro %}

fedoracommunity/client/templates/contact_us.html
<dt><h3>Contact us</h3></dt>                                                                                                   
<dd>
  <ul>
    <li> <a href="https://webchat.freenode.net/?channels=fedora-admin">#fedora-admin</a> </li>
  </ul>
</dd>

fedoracommunity/client/templates/footer.html
  <div class="container-fluid">
    <footer class="footer">
      <div>
        <div class="container text-muted">
          <div class="">
            <div class="row">
             <div class="col-sm-3">
                <dl>
                  {% include 'contact_us.html' %}
                </dl>
              </div>
              <div class="col-sm-3">
                <dl>
                  <dt><h3>Fedora Project</h3></dt>
                  <dd>
                    <ul>
                      <li> <a href="https://fedoraproject.org/wiki/Legal/TrademarkGuidelines">Trademark Guidelines</a> </li>
                      <li> <a href="https://github.com/fedora-infra/fedora-packages">Sources</a> </li>
                      <li> <a href="https://src.fedoraproject.org">Fedora Packages SRPMs</a> </li>
                    </ul>
                  </dd>
                </dl>
              </div>
              <div class="col-sm-3">
                <dl>
                  <dt><h3>Site Navigation</h3></dt>
                  <dd>
                    <ul>
                      <li> <a href="url_for('coprs_ns.coprs_show')">Home</a> </li>
                    </ul>
                  </dd>
                </dl>
              </div>
              <div class="col-sm-3">
                <dl>
                  <dt><h3>Powered by</h3></dt>
                  <dd>
                    <ul>
                      <li><a href="https://www.python.org">Python</a></li>
                      <li><a href="https://www.patternfly.org">PatternFly</a></li>
                    </ul>
                  </dd>
                </dl>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>

  <!-- FEDORA MENU -->
  {% if fedmenu_url is defined %}
  <script src="{{fedmenu_url}}/js/fedora-libravatar.js"></script>
  <script src="{{fedmenu_url}}/js/fedmenu.js"></script>
  <script>
    fedmenu({
        'url': '{{fedmenu_data_url}}',
        'mimeType': 'application/javascript',
        'position': 'bottom-right',
    });
  </script>
  {% endif %}

  {% block footer %}{% endblock %}

fedoracommunity/client/templates/header.html
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <!-- Navbar Brand -->
    <a class="navbar-brand" href="{{ url_for('main.home') }}">{{ config.APP_NAME }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <!-- Main Navigation -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
        </li>
      </ul>
      <!-- Login/Logout -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        </li>
      </ul>
    </div>
  </div>
</nav>

fedoracommunity/client/templates/search_results.html
{% extends "main/home.html" %}
{% block search_results %}

<!-- START Search Results -->
  <div class="grid_24" id="search-results-table">
    <div class="grid_12 suffix_12" id="search-notes">
      <div class="grid-controls" if="filters.search!=''">
        <div class="message template text-xs-center text-muted py-1" id="info_display">
           {{ total }} results
        </div>
      </div>
    </div>
    <table id="${w.id}" class="table">
      <tbody class="rowtemplate">
	{% for package in packages %}
        <tr class="priority4">
            <td>
                <span><a href="{{ package.url }} ">{{ package.name }}</a></span>
            </td>
            <td>
                {{ package.summary }}
            </td>
        </tr>
	  {% for subpackage in package.subpackages %}
          <tr class="subpackage">
              <td>
                  <span><a href="{{ subpackage.url }}">{{ subpackage.name }}</a></span>
              </td>
              <td>{{ subpackage.summary }}</td>
          </tr>
	  {% endfor %}
	{% endfor %}
      </tbody>
    </table>
    <div class="grid-controls">
        <div class="pager text-xs-center mb-3" id="pager"></div>
   </div>
   <script>

       function update_search_grid(search_term) {
            var grid = $("#${w.id}").mokshagrid("request_update", {"filters":{"search": search_term}});
       }

       function ready_search() {
           var search_term = "${w.filters['search']}";
           if (search_term) {
               search_term = encodeURIComponent(encodeURIComponent(search_term));
               moksha.defer(this, update_search_grid, [search_term]);
           }

       }
   </script>
</div>

<!-- END Search Results -->
{% endblock %}